# Generated by Django 4.2 on 2023-05-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
            ],
            options={"db_table": "Employee",},
        ),
    ]
