# Generated by Django 4.2 on 2023-05-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("confirm_password", models.CharField(max_length=30)),
            ],
            options={"db_table": "signup",},
        ),
    ]
