# Generated by Django 4.2 on 2023-05-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0005_remove_comment_blog_remove_comment_parent_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sno", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=12)),
                ("content", models.CharField(max_length=100)),
            ],
            options={"db_table": "contact",},
        ),
    ]
