# Generated by Django 4.2 on 2023-05-31 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0006_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="timeStamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
