# Generated by Django 4.2 on 2023-06-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0007_contact_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="content",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterModelTable(name="contact", table=None,),
    ]
