# Generated by Django 4.2 on 2023-06-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0008_alter_contact_content_alter_contact_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sno", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=30)),
                ("content", models.CharField(max_length=30)),
                ("author", models.CharField(max_length=12)),
                ("timeStamp", models.DateTimeField(blank=True)),
            ],
        ),
    ]
