# Generated by Django 4.2 on 2023-06-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0009_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="title", field=models.CharField(max_length=255),
        ),
    ]
