# Generated by Django 4.2 on 2023-06-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0016_blogcomment_remove_subcomment_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogcomment", name="parent",),
    ]
