# Generated by Django 4.2 on 2023-06-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0017_remove_blogcomment_parent"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogcomment", name="post",),
    ]
